version: '3.4'  
x-common-environment: &common-environment
  MAX_BANDWIDTH: 300000
  DEBUG_LEVEL: 0
  LOG_LEVEL: WARNING

services:
  transcoder:
    build:
      context: backend
      dockerfile: dockerfile.transcoder
    networks:
      - transcoder_network
    hostname: transcoder.local
    environment:
      <<: *common-environment
      RESTREAMER_HOST: host.docker.internal
      RESTREAMER_PORT: 8080
      TRANSCODER_PORT: 8081
  
  encoder:
    build:
      context: backend
      dockerfile: dockerfile.encoder
    networks:
      - transcoder_network
      - encoder_network
    hostname: encoder.local
    environment:
      <<: *common-environment
      TRANSCODER_HOST: transcoder.local
      TRANSCODER_PORT: 8081
      ENCODER_PORT: 8082
    depends_on:
      - transcoder

  api:
    build:
      context: backend
      dockerfile: dockerfile.api
    networks:
      - encoder_network
      - api_network
    hostname: api.local
    environment:
      <<: *common-environment
      ENCODER_HOST: encoder.local
      ENCODER_PORT: 8082
      API_PORT: 8083
    depends_on:
      - encoder
  
  webserver:
    build:
      context: webserver
      dockerfile: dockerfile
    networks:
      - webserver_network
    hostname: webserver.local
    environment:
      <<: *common-environment
      WEBSERVER_PORT: 8084
  
  nginx:
    build:
      context: nginx
      dockerfile: dockerfile
    networks:
      - nginx_network
      - webserver_network
      - api_network
    hostname: nginx.local
    environment:
      <<: *common-environment
      NGINX_PORT: 8888
      API_HOST: api.local
      API_PORT: 8083
      WEBSERVER_HOST: webserver.local
      WEBSERVER_PORT: 8084
      LOG_ADDRESS: true
      
  tor_proxy:
    build:
      context: tor
      dockerfile: dockerfile.proxy
    networks:
      - nginx_network
    environment:
      <<: *common-environment
      NGINX_HOST: nginx.local
      NGINX_PORT: 8888
      INPORT: 80
      LOG_ADDRESS: true
    depends_on:
      - nginx
  
  # tor_relay:
  #   build: 
  #     context: tor
  #     dockerfile: dockerfile.relay
  #   environment:
  #     <<: *common-environment
  
  i2p:
    build:
      context: i2p
      dockerfile: dockerfile
    networks:
      - nginx_network
    environment:
      <<: *common-environment
      NGINX_HOST: nginx.local
      NGINX_PORT: 8888
      INPORT: 80
      LOG_ADDRESS: true
    depends_on:
      - nginx

networks:
  transcoder_network:
    driver: bridge
  encoder_network:
    driver: bridge
  api_network:
    driver: bridge
  webserver_network:
    driver: bridge
  nginx_network:
    driver: bridge
