FROM python:3.12-slim-bookworm

RUN useradd -m runner
USER runner

RUN pip3 install --upgrade pip \
    && pip3 install --upgrade pydantic pycryptodome

COPY ./lib /app/lib
COPY encoder.py /app

WORKDIR /app
CMD python3 encoder.py