import logging

SERVER_NAME = "OnionStream_a0823"
DEFAULT_HLS_SEGMENT_DURATION = 5
DEFAULT_HLS_PLAYLIST_LENGTH = 4
DEFAULT_ENCRYPTION_KEY_ROTATION_INTERVAL = 60
DEFAULT_LOG_LEVEL = logging.WARNING

POST_MORTEM_DEBUGGER = False

MAX_KEY_RETRY = 5
KEY_RETRY_TIMEOUT = 5

DEBUG_FORCE_IV = None
DEBUG_SHOW_KEY = False

RESTREAMER_HOST = "127.0.0.1"
RESTREAMER_PORT = 8080

TRANSCODER_HOST = "127.0.0.1"
TRANSCODER_PORT = 8081

ENCODER_HOST = "127.0.0.1"
ENCODER_PORT = 8082

API_HOST = "127.0.0.1"
API_PORT = 8083
