FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y wget gnupg gettext apt-transport-https dos2unix \
    && wget -q -O- https://repo.i2pd.xyz/r4sas.gpg | gpg --dearmor > /usr/share/keyrings/purplei2p.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/purplei2p.gpg] https://repo.i2pd.xyz/debian bookworm main" > /etc/apt/sources.list.d/purplei2p.list \
    && echo "# deb-src [signed-by=/usr/share/keyrings/purplei2p.gpg] https://repo.i2pd.xyz/debian bookworm main" >> /etc/apt/sources.list.d/purplei2p.list \
    && apt-get update \
    && apt-get install -y i2pd

COPY main.sh /i2p/main.sh
COPY tunnels.conf.template /i2p/tunnels.conf.template

RUN dos2unix /i2p/main.sh \
    && dos2unix /i2p/tunnels.conf.template

RUN chmod +x /i2p/main.sh \
    && chown -R i2pd:i2pd /i2p

USER i2pd

RUN mkdir -p /i2p/keys \
    && mkdir -p /var/lib/i2pd/.i2pd/keys \
    && ln -s /i2p/keys /var/lib/i2pd/.i2pd/keys

WORKDIR /i2p

CMD ./main.sh
